# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Loceat' do
  use_frameworks!

  pod 'GoogleMaps'

  target 'LoceatTests' do
    inherit! :search_paths
  end

  target 'LoceatUITests' do
  end

end
